# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'x.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(589, 509)
        self.IP = QtWidgets.QLabel(Form)
        self.IP.setGeometry(QtCore.QRect(20, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.IP.setFont(font)
        self.IP.setObjectName("IP")
        self.Username = QtWidgets.QLabel(Form)
        self.Username.setGeometry(QtCore.QRect(20, 140, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Username.setFont(font)
        self.Username.setObjectName("Username")
        self.DBName = QtWidgets.QLabel(Form)
        self.DBName.setGeometry(QtCore.QRect(20, 170, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DBName.setFont(font)
        self.DBName.setObjectName("DBName")
        self.IP_LBL = QtWidgets.QLineEdit(Form)
        self.IP_LBL.setGeometry(QtCore.QRect(130, 70, 441, 20))
        self.IP_LBL.setObjectName("IP_LBL")
        self.DB_LBL = QtWidgets.QLineEdit(Form)
        self.DB_LBL.setGeometry(QtCore.QRect(130, 180, 441, 20))
        self.DB_LBL.setObjectName("DB_LBL")
        self.USR_LBL = QtWidgets.QLineEdit(Form)
        self.USR_LBL.setGeometry(QtCore.QRect(130, 140, 441, 20))
        self.USR_LBL.setObjectName("USR_LBL")
        self.DBName_2 = QtWidgets.QLabel(Form)
        self.DBName_2.setGeometry(QtCore.QRect(20, 100, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DBName_2.setFont(font)
        self.DBName_2.setObjectName("DBName_2")
        self.COUNT_LBL = QtWidgets.QLineEdit(Form)
        self.COUNT_LBL.setGeometry(QtCore.QRect(130, 100, 441, 20))
        self.COUNT_LBL.setObjectName("COUNT_LBL")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(130, 260, 451, 221))
        self.textEdit.setObjectName("textEdit")
        self.DBName_3 = QtWidgets.QLabel(Form)
        self.DBName_3.setGeometry(QtCore.QRect(130, 230, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DBName_3.setFont(font)
        self.DBName_3.setObjectName("DBName_3")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(20, 350, 75, 23))
        self.start.setObjectName("start")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.IP.setText(_translate("Form", "Server IP:"))
        self.Username.setText(_translate("Form", "Username:"))
        self.DBName.setText(_translate("Form", "DBName:"))
        self.DBName_2.setText(_translate("Form", "Count:"))
        self.DBName_3.setText(_translate("Form", "..."))
        self.start.setText(_translate("Form", "Başlat"))
        self.label.setText(_translate("Form", "Turan Güçlü Brute Force"))

